### ISSUE TITLE
small optimization to the shift-and-add multiply routines?

### ISSUE THREAD

**Issue by jbrandwood** [TobyLobster/multiply_test#2]
Thank you for all your work on these tests, it is fun to see all of the different little tweaks that people have tried to speed up the basic multiply algorithm! :-)

Personally, I like to rearrange the mult2.a codeflow so that I can apply a small branch-optimization that saves -2 cycles per multiplier_1_bit and -1 cycles per multiplier_0_bit, with a cost of +2 cycles on the final loop, which is an overall win.

The optimization relies on the first rotation of the multiplier putting a 0 into its top bit, which nearly every shift-and-add variation does, so that the final Y==0 condition is always matched with carry-clear.

I also tend to copy the first shift to the top, as do some of the other multiply routines, but that isn't required.

This optimization can be applied to a variety of the different shift-and-add flows, and here is my modified mult2.a ...

```
mult
    lda #0                          ; A holds the low byte of ext (zero for now)
    sta ext+1                       ; high byte of ext = 0
    ldy #16                         ; loop counter. Loop 16 times.

    lsr acc+1                       ; } acc_ext >> 1
    ror acc                         ; }
    bcc loop

add
    clc                             ;               }
    adc aux                         ;               }
    tax                             ; remember A    }
    lda aux+1                       ;               } ext += aux
    adc ext+1                       ;               }
    sta ext+1                       ;               }
    txa                             ; recall A

loop
    ror ext+1                       ; }
    ror                             ; }
    ror acc+1                       ; } acc_ext >> 1
    ror acc                         ; }

    dey                             ; decrement loop counter
    bcs add                         ; jump if carry set
    bne loop                        ; loop back if not done yet

    sta ext                         ;
    rts                             ;

```

**Comment by TobyLobster** [comment]
Thanks. Yes, you are right. On the plus side you do get better performance with your code, but it uses a few more bytes. It is a competitive method so I've added this code to the results as mult85.a. It looks like a similar approach as mult1.a, but more efficient.

**Comment by jbrandwood** [comment]
Thanks! :-) It's only a small optimization, and may not be worth the added bytes, especially on the 6502/65C02.

On the HuC6280 (65C02 derivative) it's a clearer, but still small, win because our branch-taken cost is 4-cycles instead of the regular 6502's 3-cycles.
