### ISSUE TITLE
Improve speed of smult9

### ISSUE THREAD

**Issue by fredrikr** [TobyLobster/multiply_test#5]
Thanks for your great work on this, we've used your findings to make Z-machine multiplication faster in Ozmoo.

Specifically, we're now using smult9. We're butchering it a bit, because we're only interested in a 16-bit result though.

It seems to me that you can make it faster by flipping the bits when storing the multiplier in result.  So, add two EOR #$FF in this part, change the BCC to BCS in the main loop, and skip the CLC before the addition:

https://github.com/TobyLobster/multiply_test/blob/1cc7b819ace303c9cb1bc001ff936d0e65f1f7f3/tests/smult9.a#L55-L58

**Comment by TobyLobster** [comment]
Hi, thanks for the feedback. I like your idea to skip the clc by using an inverted carry value, but I think when the bcs branch is taken the incorrect (set) carry value will get shifted into the result here:
https://github.com/TobyLobster/multiply_test/blob/1cc7b819ace303c9cb1bc001ff936d0e65f1f7f3/tests/smult9.a#L84-L86

**Comment by fredrikr** [comment]
Ah, I believe you are right. That part was a bit muddy to me. I thought the first ROR could have been an LSR instead, but I guess not.

(Also, I think we will actually get away with this bit flipping because we throw away the top 16 bits of the result)
